# Stage 1: Base image with common dependencies
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04
# FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

# Prevents prompts from packages asking for user input during installation
ENV DEBIAN_FRONTEND=noninteractive
# Prefer binary wheels over source distributions for faster pip installations
ENV PIP_PREFER_BINARY=1
# Ensures output from python is printed immediately to the terminal without buffering
ENV PYTHONUNBUFFERED=1 
# Speed up some cmake builds
ENV CMAKE_BUILD_PARALLEL_LEVEL=8

# 不要檢查 CUDA 版本
ENV NVIDIA_DISABLE_REQUIRE=1

ENV ROOT=/app

# Install Python, git and other necessary tools
RUN apt-get update && apt-get install -y \
	python3-dev python3-pip pipx git wget \
	zip unzip libgl1 libglib2.0-0 libsm6 \
	libxrender1 libxext6 ffmpeg

# Clean up to reduce image size
RUN apt-get autoremove -y && \
	apt-get clean -y && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install comfy-cli
RUN python3 -m pip install --no-cache-dir \
	comfy-cli

# RUN git clone https://github.com/comfyanonymous/ComfyUI.git ComfyUI
COPY ./ComfyUI /app/ComfyUI

RUN cd ./ComfyUI && \
	python3 -m pip install -r requirements.txt --no-cache-dir

# Change working directory to ComfyUI
WORKDIR /app/ComfyUI

# Install Python dependencies (Worker Template)
COPY builder/requirements.txt ${ROOT}/requirements.txt
RUN python3 -m pip install --upgrade pip && \
	python3 -m pip install --upgrade -r ${ROOT}/requirements.txt --no-cache-dir && \
	rm ${ROOT}/requirements.txt

COPY src ${ROOT}/

RUN rm ${ROOT}/test_input.json || true

# Create necessary directories
RUN mkdir -p models/checkpoints models/vae models/diffusion_models models/clip models/text_encoders models/LLM input

COPY ./SafeTensors/lightricksLTXV_2b091.safetensors /app/ComfyUI/models/checkpoints/
COPY ./SafeTensors/stableDiffusion3SD3_textEncoderT5XXLFP16.safetensors /app/ComfyUI/models/clip/
COPY ./PixArt-XL-2-1024-MS /app/ComfyUI/models/text_encoders/PixArt-XL-2-1024-MS/
COPY ./LLM /app/ComfyUI/models/LLM/

COPY ./placeholder_video.mp4 /app/ComfyUI/input/
COPY ./placeholder_image.png /app/ComfyUI/input/

RUN cd ./custom_nodes && \
	git clone https://github.com/ltdrdata/ComfyUI-Manager.git && \
	git clone https://github.com/Lightricks/ComfyUI-LTXVideo.git && \
	git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git && \
	git clone https://github.com/SeanScripts/ComfyUI-Unload-Model.git

RUN cd ./custom_nodes && \
	python3 -m pip install --no-cache-dir -r ComfyUI-LTXVideo/requirements.txt \
	-r ComfyUI-VideoHelperSuite/requirements.txt

RUN cd ./custom_nodes && \
	git clone https://github.com/WASasquatch/was-node-suite-comfyui.git && \
	git clone https://github.com/kijai/ComfyUI-Florence2.git && \
	git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git && \
	git clone https://github.com/M1kep/ComfyLiterals.git && \
	git clone https://github.com/DoctorDiffusion/ComfyUI-MediaMixer.git && \
	git clone https://github.com/kijai/ComfyUI-KJNodes.git && \
	git clone https://github.com/melMass/comfy_mtb.git && \
	git clone https://github.com/theUpsider/ComfyUI-Logic.git

RUN cd ./custom_nodes && \
	python3 -m pip install --no-cache-dir -r was-node-suite-comfyui/requirements.txt \
	-r ComfyUI-Florence2/requirements.txt \
	-r ComfyUI-MediaMixer/requirements.txt \
	-r ComfyUI-KJNodes/requirements.txt \
	-r comfy_mtb/requirements.txt

WORKDIR ${ROOT}
ENV NVIDIA_VISIBLE_DEVICES=all
ENV CLI_ARGS=""

RUN chmod +x ${ROOT}/start.sh

EXPOSE 8188

# Start the container
CMD ["sh","/app/start.sh"]
